[package]
name = "mux-client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "wmux"
path = "src/main.rs"

[dependencies]
mux-cli = { path = "../mux-cli", package = "mux-cli" }
mux-platform = { path = "../mux-platform", package = "mux-platform" }
mux-platform-windows = { path = "../mux-platform-windows", package = "mux-platform-windows" }
mux-protocol = { path = "../mux-protocol", package = "mux-protocol" }

[lints]
workspace = true
