[package]
name = "wmux"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "wmux"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
wmux-config = { path = "../wmux-config" }
wmux-cli = { path = "../wmux-cli" }
wmux-platform = { path = "../wmux-platform" }
wmux-protocol = { path = "../wmux-protocol" }
wmux-windows = { path = "../wmux-windows" }

[lints]
workspace = true
