[package]
name = "wmux-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "wmux_core"
path = "src/lib.rs"

[dependencies]
smallvec.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
vte.workspace = true
wmux-platform = { path = "../wmux-platform" }

[lints]
workspace = true
