[package]
name = "wmux-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[[bin]]
name = "wmux-bench"
path = "src/main.rs"

[dependencies]
wmux-core = { path = "../wmux-core", version = "=1.0.4" }
wmux-platform = { path = "../wmux-platform", version = "=1.0.4" }
wmux-protocol = { path = "../wmux-protocol", version = "=1.0.4" }

[lints]
workspace = true
