[package]
name = "mux-platform-unix"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "mux_platform_unix"
path = "src/lib.rs"

[dependencies]
mux-platform = { path = "../mux-platform", package = "mux-platform" }

[lints]
workspace = true
