[package]
name = "wmux-unix"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[lib]
name = "wmux_unix"
path = "src/lib.rs"

[dependencies]
crossterm = { workspace = true, features = ["use-dev-tty"] }
libc.workspace = true
nix.workspace = true
tokio.workspace = true
wmux-platform = { path = "../wmux-platform", version = "=1.0.16" }

[target.'cfg(unix)'.dependencies]
close_fds.workspace = true

[dev-dependencies]
wmux-config = { path = "../wmux-config", version = "=1.0.16" }
wmux-protocol = { path = "../wmux-protocol", version = "=1.0.16" }
wmux-server = { path = "../wmux-server", version = "=1.0.16" }

[lints]
workspace = true
