[package]
name = "wmux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[package.metadata.dist]
dist = true

[[bin]]
name = "wmux"
path = "src/main.rs"

[[bin]]
name = "wmux-server"
path = "src/server_main.rs"

[lib]
name = "wmux_client"
path = "src/lib.rs"

[dependencies]
tokio.workspace = true
wmux-config = { path = "../wmux-config", version = "=1.0.11" }
wmux-core = { path = "../wmux-core", version = "=1.0.11" }
wmux-cli = { path = "../wmux-cli", version = "=1.0.11" }
wmux-platform = { path = "../wmux-platform", version = "=1.0.11" }
wmux-protocol = { path = "../wmux-protocol", version = "=1.0.11" }
wmux-server = { path = "../wmux-server", version = "=1.0.11" }

[target.'cfg(windows)'.dependencies]
wmux-windows = { path = "../wmux-windows", version = "=1.0.11" }

[target.'cfg(unix)'.dependencies]
wmux-unix = { path = "../wmux-unix", version = "=1.0.11" }

[lints]
workspace = true
