[package]
name = "mux-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "wmux-server"
path = "src/main.rs"

[dependencies]
mux-core = { path = "../mux-core", package = "mux-core" }
mux-platform = { path = "../mux-platform", package = "mux-platform" }
mux-platform-windows = { path = "../mux-platform-windows", package = "mux-platform-windows" }
mux-protocol = { path = "../mux-protocol", package = "mux-protocol" }

[lints]
workspace = true
