[package]
name = "wmux-windows"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[lib]
name = "wmux_windows"
path = "src/lib.rs"

[dependencies]
crossterm.workspace = true
tokio.workspace = true
windows-sys.workspace = true
wmux-platform = { path = "../wmux-platform", version = "=1.0.3" }

[dev-dependencies]
wmux-config = { path = "../wmux-config", version = "=1.0.3" }
wmux-protocol = { path = "../wmux-protocol", version = "=1.0.3" }
wmux-server = { path = "../wmux-server", version = "=1.0.3" }

[lints]
workspace = true
