[package]
name = "wmux-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]
tokio.workspace = true
wmux-config = { path = "../wmux-config", version = "=1.0.6" }
wmux-core = { path = "../wmux-core", version = "=1.0.6" }
wmux-platform = { path = "../wmux-platform", version = "=1.0.6" }
wmux-protocol = { path = "../wmux-protocol", version = "=1.0.6" }

[lints]
workspace = true
